server:
  port: 10000

spring:
  application:
    name: scp-eureka-server
  security:
    user:
      name: admin
      password: admin

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true  # 将自己的IP注册到Eureka Server, false注册操作系统的hostname
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 将Instance ID设置成IP:端口的形式
  client:
    register-with-eureka: false #表示是否将自己注册到 Eureka Server，默认为 true。
    fetch-registry: false #表示是否从 Eureka Server 获取注册信息，默认为 true。
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址。多个地址可使用英文逗号（,）分隔。
           
